//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPlayground.Wpf {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPlayground.Wpf.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ul{list-style:none}
        ///#proList li{background:lime;}
        ///#conList li{background:crimson;}.
        /// </summary>
        internal static string CssContent {
            get {
                return ResourceManager.GetString("CssContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Pros and Cons&lt;/h1&gt;
        ///&lt;table&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;
        ///  &lt;h2&gt;Pros&lt;/h2&gt;
        ///&lt;/td&gt;
        ///&lt;td&gt;
        ///   &lt;h2&gt;Cons&lt;/h2&gt;
        ///&lt;/td&gt;
        ///&lt;/tr&gt;
        ///
        ///&lt;tr&gt;
        ///&lt;td&gt;
        ///&lt;input type=&quot;text&quot; id=&quot;proInput&quot;&gt;
        ///  &lt;button onclick=&quot;addPro()&quot;&gt;Add&lt;/button&gt;
        ///&lt;/td&gt;
        ///&lt;td&gt;
        ///  &lt;input type=&quot;text&quot; id=&quot;conInput&quot;&gt;
        ///  &lt;button onclick=&quot;addCon()&quot;&gt;Add&lt;/button&gt;
        ///
        ///&lt;/td&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt; &lt;ul id=&quot;proList&quot;&gt;&lt;/ul&gt;&lt;/td&gt;
        ///&lt;td&gt;  &lt;ul id=&quot;conList&quot;&gt;&lt;/ul&gt;&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string HtmlBody {
            get {
                return ResourceManager.GetString("HtmlBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function addPro() {
        ///      var proInput = document.getElementById(&quot;proInput&quot;);
        ///      var proList = document.getElementById(&quot;proList&quot;);
        ///
        ///      var proText = proInput.value;
        ///      if (proText.trim() !== &quot;&quot;) {
        ///        var listItem = document.createElement(&quot;li&quot;);
        ///        listItem.textContent = proText;
        ///        proList.appendChild(listItem);
        ///        proInput.value = &quot;&quot;;
        ///      }
        ///    }
        ///
        ///    function addCon() {
        ///      var conInput = document.getElementById(&quot;conInput&quot;);
        ///      var conList = document.getE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JSContent {
            get {
                return ResourceManager.GetString("JSContent", resourceCulture);
            }
        }
    }
}
